"""empty message

Revision ID: 7e979d970d05
Revises: 
Create Date: 2019-01-24 11:33:36.426854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e979d970d05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scales',
    sa.Column('scale_name', sa.String(length=150), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('stop', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('scale_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scales')
    # ### end Alembic commands ###
